# Gradle daemon
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Test JVM: Spring Boot context + Testcontainers в одном процессе требуют явных границ
org.gradle.jvmargs.windows=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Контейнер Testcontainers
org.testcontainers.docker.client.strategy=BinaryTreeStrategy
testcontainers.reuse.enable=false
