-- Справочник типов начислений OZON.
--
-- Снимок ответа POST /v1/finance/accrual/types на 2026-09-30 (132 типа).
-- Посеян, чтобы аналитика могла называть расходы без обращения к API.
-- Это не замена справочнику: syncAccrualTypes() обновляет строки из API,
-- поэтому появление новых или переименование типов не потребует миграции.
-- Уникальность (marketplace_id, external_type_id) делает повторный запуск безопасным.

INSERT INTO accrual_type (marketplace_id, external_type_id, name, description)
SELECT m.id, t.external_type_id, t.name, t.description
FROM (VALUES
    (1, 'Acquiring', 'Эквайринг'),
    (2, 'BackwardShipment', 'Обратная магистраль'),
    (3, 'BrandCommission', 'Продвижение бренда'),
    (4, 'BrandPromotion', 'Подключение продвижения бренда'),
    (5, 'BrandShelf', 'Брендовая полка'),
    (6, 'Cancellation', 'Обработка отменённых и невостребованных товаров'),
    (7, 'Charity', 'Благотворительное пожертвование'),
    (8, 'ClaimCommission', 'Начисления по претензиям'),
    (9, 'ClientReturn', 'Обработка возвратов'),
    (10, 'Compensation', 'Компенсация'),
    (11, 'CorrectionCommission', 'Инвентаризация взаиморасчетов'),
    (12, 'CrossDock', 'Кросс-докинг'),
    (13, 'CrossDockPickUpCourierDelivery', 'Организация выезда курьера'),
    (14, 'DefectRate', 'Обработка операционных ошибок продавца'),
    (15, 'Disposal', 'Утилизация'),
    (16, 'Drop-Off', 'Обработка отправления Drop-off'),
    (17, 'Drop-Off Agent', 'Обработка отправления Drop-off партнёрами'),
    (18, 'EarlyPayment', 'Досрочная выплата'),
    (19, 'ExternalPromotion', 'Внешнее продвижение'),
    (20, 'FlexiblePayments', 'Гибкий график выплат'),
    (21, 'Fulfillment', 'Сборка заказа'),
    (22, 'Installment', 'Рассрочка'),
    (23, 'InternetSiteAdvertising', 'Реклама в сети Интернет на Сайте'),
    (24, 'ItemCloning', 'Перенос карточек товаров'),
    (25, 'ItemCompensation', 'Товарная компенсация'),
    (26, 'KazakhstanBuyerInstallment', 'Рассрочка для покупателей из Казахстана'),
    (27, 'LabelOriginal', 'Бейдж Оригинал'),
    (28, 'LastMile', 'Последняя миля'),
    (29, 'LastMileCourier', 'Доставка до места выдачи'),
    (30, 'LastMilePickUpPoint', 'Выдача товара'),
    (31, 'LeadGeneration', 'Лидогенерация для автодилеров'),
    (32, 'Logistic', 'Логистика'),
    (33, 'Marketing', 'Рекламные услуги'),
    (34, 'Marking', 'Обязательная маркировка товаров'),
    (35, 'Moderation', 'Модерация товаров'),
    (36, 'OrdersBooking', 'Привлечение предварительных заказов'),
    (37, 'OzonData', 'Ozon Data'),
    (38, 'PackageCost', 'Обеспечение материалами для упаковки товара'),
    (39, 'PackingFee', 'Упаковка товара партнёрами'),
    (40, 'PartialReturn', 'Обработка частичного невыкупа'),
    (41, 'PayPerClick', 'Оплата за клик'),
    (42, 'Pick-Up', 'Обработка отправления Pick-up'),
    (43, 'PickUpCourierArrangement', 'Организация выезда курьера'),
    (44, 'PickUpCourierDelivery', 'Доставка курьером Pick-up'),
    (45, 'PickUpPointReturnAcceptance', 'Обработка возвратов, отмен и невыкупов партнёрами'),
    (46, 'Placements', 'Размещение товаров на складах Ozon'),
    (47, 'PointsForReviews', 'Баллы за отзывы'),
    (48, 'PremiumCashbackIndividualPoints', 'Бонусы продавца'),
    (49, 'PremiumCashbackPromotion', 'Услуга продвижения Premium'),
    (50, 'PremiumMailingCommission', 'Бонусы продавца - рассылка'),
    (51, 'PremiumMembership', 'Подписка Premium Pro (процент)'),
    (52, 'PremiumSubscription', 'Подписка Premium'),
    (53, 'PreparingToReturn', 'Подготовка товаров к возврату'),
    (54, 'Promotion', 'Продвижение товара'),
    (55, 'PushCampaign', 'Рассылка пуш-уведомлений'),
    (56, 'QuantProcessingDrop', 'Обработка и логистика кванта'),
    (57, 'RealizationReportCorrection', 'Корректировка стоимости услуг'),
    (58, 'Replenishment', 'Перемещение товаров между складами Ozon'),
    (59, 'ReturnFlowLogistic', 'Обратная логистика'),
    (60, 'ReturnStorageInTheWarehouse', 'Долгосрочное размещение возврата FBS'),
    (61, 'ReviewsPin', 'Закрепление отзыва'),
    (62, 'RfbsClientDeliveryCharge', 'Перечисление за доставку от покупателя'),
    (63, 'RfbsDomesticAgentFee', 'Агентское вознаграждение Ozon Агрегатор realFBS'),
    (64, 'RfbsDomesticDelivery', 'Доставка Партнёром Ozon'),
    (65, 'RfbsEasyReturn', 'Лёгкий возврат'),
    (66, 'RfbsGlobalAgentFee', 'Агентское вознаграждение Ozon'),
    (67, 'RfbsGlobalDelivery', 'Услуги международной доставки'),
    (68, 'RfbsServiceFee', 'Сервисный сбор за интеграцию с логистической платформой'),
    (69, 'SaleCommission', 'Вознаграждение за продажу'),
    (70, 'SaleReview', 'Приобретение отзывов на платформе'),
    (71, 'SellerReturns', 'Вывоз товара со склада силами Ozon'),
    (72, 'SetOff', 'Взаимозачет требований между Договорами'),
    (73, 'Shipment', 'Магистраль'),
    (74, 'StarsMembership', 'Звёздные товары'),
    (75, 'Stencil', 'Трафареты'),
    (76, 'StockInsurance', 'Страхование товара от массовых повреждений'),
    (77, 'SupplyInbound', 'Обработка товара'),
    (78, 'TemporaryPlacement', 'Краткосрочное размещение возврата FBS'),
    (79, 'TemporaryPlacementsAgent', 'Временное размещение товара партнерами'),
    (80, 'VideoCover', 'Генерация видеообложки'),
    (81, 'VolumeObligationReward', 'Бонус за достижение цели продаж'),
    (82, 'VolumeWeightCharacteristicsProcessing', 'Дополнительная обработка ОВХ'),
    (83, 'BrandDeposit', 'Обеспечительные платежи'),
    (84, 'ItemPacking', 'Дополнительная упаковка на складе Ozon'),
    (85, 'ItemSealing', 'Пломбирование товара'),
    (86, 'PackmanCisPacking', 'Дополнительная упаковка товара на ПВЗ в СНГ'),
    (87, 'SocialMediaAdvertising', 'Реклама в социальных сетях'),
    (88, 'ClickAndCollect', 'Самовывоз'),
    (89, 'DefectFineModeration', 'Запрещённый контент'),
    (90, 'DefectFineProhibitedGoods', 'Запрещённый товар'),
    (91, 'DefectFineCounterfeitGoods', 'Товар с нарушением интеллектуальных прав'),
    (92, 'DefectFineComplaint', 'Жалобы покупателей'),
    (93, 'DefectFineErrors', 'Превышение индекса ошибок'),
    (94, 'DefectFineShipmentDelayRate', 'Отгрузка в нерекомендованный слот'),
    (95, 'CustomerReviews', 'Подписка Управление отзывами'),
    (96, 'AcceleratedReviewCollection', 'Ускоренный сбор отзывов'),
    (97, 'PackageUnitProcessing', 'Обработка грузоместа'),
    (98, 'DeliveryToHandoverPlaceByOzon', 'Доставка до места выдачи силами Ozon'),
    (99, 'InternationalLogisticDelta', 'Международная логистика'),
    (100, 'OzonGlobalLogisticsDelivery', 'Транспортно-экспедиционная услуга по организации международной перевозки'),
    (101, 'OversizedExtraHandling', 'Обработка нестандартного товара'),
    (102, 'B2CTemporaryPlacement', 'Временное размещение отправления в СЦ/ПВЗ/партнёрами'),
    (103, 'B2CDisposal', 'Утилизация отправления'),
    (104, 'B2CInsuranceCompensation', 'Страховое возмещение'),
    (105, 'B2CInsuranceShipping', 'Страхование отправления'),
    (106, 'B2C Drop-Off', 'B2C Обработка отправления Drop-off'),
    (107, 'B2C Drop-Off Agent', 'B2C Обработка отправления Drop-off партнёрами'),
    (108, 'B2CContainerPacking', 'Обеспечение материалами для упаковки отправления'),
    (109, 'B2CContainerPackage', 'Упаковка отправления партнёрами'),
    (110, 'B2CCourierClientReinvoice', 'B2C Доставка до места выдачи партнёрами'),
    (111, 'B2CDeliveryToHandoverPlaceByOzon', 'B2C Доставка до места выдачи силами Ozon'),
    (112, 'B2CPickUpPointClientReinvoice', 'B2C Выдача товара партнёрами'),
    (113, 'B2CPickUpPointReturnAcceptance', 'B2C Обработка возвратов, отмен и невыкупов партнёрами'),
    (114, 'B2CLogistics', 'B2C Логистика'),
    (115, 'B2CBackwardLogistics', 'B2C Обратная логистика'),
    (116, 'FirstCustomerReview', 'Сбор первых отзывов'),
    (117, 'IncreaseAssortmentLimit', 'Увеличение лимита на создание карточек товаров'),
    (118, 'LabelBrandVerified', 'Бейдж «Бренд проверен»'),
    (119, 'CustomerChatPoints', 'Баллы в чате с покупателем'),
    (120, 'CourierPickUpByOzon', 'Доставка до СЦ силами Ozon'),
    (121, 'CourierPickUpReinvoice', 'Доставка до СЦ партнёрами'),
    (122, 'RfbsGlobalIntermediaryService', 'Услуги по заключению договора на организацию международной перевозки'),
    (123, 'RfbsGlobalPlatformConnectionService', 'Электронная услуга подключения к логистической Платформе Ozon'),
    (124, 'RfbsBuyerDelivery', 'Перечисление за доставку от покупателя'),
    (125, 'AnalyticsLite', 'Аналитика Lite'),
    (126, 'AnalyticsPremium', 'Аналитика Premium'),
    (127, 'AnalyticsPlus', 'Аналитика Plus'),
    (128, 'AnalyticsPro', 'Аналитика Pro'),
    (129, 'AnalyticsCorrection', 'Корректировка стоимости услуг'),
    (130, 'DisplayAdvertisingPlacement', 'Размещение медийной рекламы'),
    (131, 'MicroFulfillmentSupply', 'Приёмка товара партнёрами'),
    (132, 'MicroFulfillmentPicking', 'Подготовка товара к отгрузке партнёрами')
) AS t(external_type_id, name, description)
CROSS JOIN marketplace m
WHERE m.code = 'OZON'
ON CONFLICT (marketplace_id, external_type_id) DO UPDATE
    SET name = EXCLUDED.name, description = EXCLUDED.description, updated_at = now();

